version: '2.2'

volumes:
  esdata1:
    driver: local
  kbdata1:
    driver: local

networks:
  esnet:

services:
  elasticsearch:
    build: ./elasticsearch-5.5.3-with-plugins
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms7g -Xmx7g"
      - xpack.security.enabled=false
    ulimits:
      nproc: 3000
      nofile: 65536
      memlock: -1
    mem_limit: 8g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.3
    environment:
      - SERVER_NAME=localhost
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - 5601:5601
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - esnet
    volumes:
      - kbdata1:/usr/share/kibana/data
